# Generated by Django 3.2.7 on 2021-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(upload_to='blog_images')),
                ('pub_desc', models.CharField(max_length=1500)),
                ('publisher_name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
