# Generated by Django 3.2.9 on 2022-04-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_auto_20220411_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('Books', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lib_app.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
