# Generated by Django 3.2.9 on 2022-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='date',
            field=models.DateField(auto_created=True, blank=True),
        ),
    ]
