# Generated by Django 3.2.7 on 2021-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('dastination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
