# Generated by Django 3.2.7 on 2022-01-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1200)),
                ('image', models.ImageField(upload_to='family_images')),
                ('food', models.ImageField(max_length=200, upload_to='')),
                ('decoration', models.ImageField(max_length=200, upload_to='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1200)),
                ('image', models.ImageField(upload_to='culture_images')),
                ('food', models.ImageField(max_length=200, upload_to='')),
                ('decoration', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1200)),
                ('image', models.ImageField(upload_to='charity_images')),
                ('food', models.ImageField(max_length=200, upload_to='')),
                ('sponser', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1200)),
                ('image', models.ImageField(upload_to='culture_images')),
                ('food', models.ImageField(max_length=200, upload_to='')),
                ('publicity', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('people', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('Event', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=1200)),
                ('message', models.TextField(max_length=1200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
