# Generated by Django 3.2.7 on 2022-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_contactus_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
