# Generated by Django 3.2.7 on 2022-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_bookevent_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='people',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='food',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='charity',
            name='food',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='culture',
            name='food',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='decoration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='food',
            field=models.CharField(max_length=200),
        ),
    ]
