# Generated by Django 3.2.7 on 2022-01-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_auto_20220128_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookevent',
            old_name='Event',
            new_name='event',
        ),
    ]
