# Generated by Django 3.2.7 on 2022-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_rename_event_bookevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='food',
            field=models.CharField(default='', max_length=150),
        ),
    ]
