# Generated by Django 3.2.7 on 2022-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('desc', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
